site_name: Humanities Mapping
theme:
  name: material
  font:
    text: Libre Franklin
  icon:
    logo: fontawesome/brands/pagelines
  favicon: images/favicon.png
  palette:
  - media: '(prefers-color-scheme: light)'
    scheme: default
    primary: blue grey
    accent: light blue
    toggle:
      icon: material/leaf-circle
      name: Switch to light mode
  - media: '(prefers-color-scheme: dark)'
    scheme: slate
    primary: blue grey
    accent: light blue
    toggle:
      icon: material/leaf-circle-outline
      name: Switch to dark mode
  features:
  - search.suggest
  - search.highlight
  - content.tabs.link
extra:
  generator: false

nav:
- ğŸŒ± Projects: day1.md
- ğŸŒ¿ Data: day2.md
- ğŸ Maps: day3.md
- ğŸ‚ DH+Maps: day4.md
