site_name: Humanities Mapping
repo_url: https://apjanco.github.io/leaflet-course/
repo_name: apjanco/leaflet-course
theme:
  name: material
  font:
    text: Libre Franklin
  icon:
    logo: fontawesome/brands/pagelines
  favicon: images/favicon.png
  palette:
  - media: '(prefers-color-scheme: light)'
    scheme: default
    primary: blue grey
    accent: light blue
    toggle:
      icon: material/leaf-circle
      name: Switch to light mode
  - media: '(prefers-color-scheme: dark)'
    scheme: slate
    primary: blue grey
    accent: light blue
    toggle:
      icon: material/leaf-circle-outline
      name: Switch to dark mode
  features:
  - search.suggest
  - search.highlight
  - content.tabs.link
extra:
  generator: false

nav:
- ğŸŒ± June 5: day1.md
- ğŸŒ¿ June 6: day2.md
- ğŸ June 7: day3.md
- ğŸ‚ June 8: day4.md
